example-1:
	gcc data-section-c-only.c

example-1-no-link:
	gcc -c data-section-c-only.c

example-2:
	gcc data-section.S data-section-with-arm.c

example-2-no-link:
	gcc -c data-section.S data-section-with-arm.c

clean:
	rm *.o *.out